/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Model;

/**
 *
 * @author LENOVO
 */
public class Branch 
{
    private int branchID;
    private String branchName;
    private String city;
    private String address;
    private String phoneNumber;
    private int num_of_employees;
    private int managerID; // Foreign Key reference to Employee
    private boolean isActive;

    public Branch(String branchName, String city, String address, String phoneNumber) 
    {// these things in the constructor needs to be taken to create a new branch
        this.branchName = branchName;
        this.city = city;
        this.address = address;
        this.phoneNumber = phoneNumber;
        this.isActive=true;
        this.num_of_employees=0;
        //manager id null initially
        //id generated serially by db
    }

    public Branch(int branchID, String branchName, String city, String address, String phoneNumber, int num_of_employees, int managerID, boolean isActive) 
    {
        this.branchID = branchID;  //id would be generated by db
        this.branchName = branchName;
        this.city = city;
        this.address = address;
        this.phoneNumber = phoneNumber;
        this.num_of_employees = num_of_employees;  //initial number of employees would be zero
        this.managerID = managerID; //id from manager table
        this.isActive = isActive; //initially it is active
    }
    
    public int getBranchID() 
    {
        return branchID;
    }

    public void setBranchID(int branchID) 
    {
        this.branchID = branchID;
    }

    public String getBranchName()
    {
        return branchName;
    }

    public void setBranchName(String branchName)
    {
        this.branchName = branchName;
    }

    public String getCity() 
    {
        return city;
    }

    public void setCity(String city) 
    {
        this.city = city;
    }

    public String getAddress()
    {
        return address;
    }

    public void setAddress(String address) 
    {
        this.address = address;
    }

    public String getPhoneNumber()
    {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber)
    {
        this.phoneNumber = phoneNumber;
    }

    public int getNum_of_employees() 
    {
        return num_of_employees;
    }

    public void setNum_of_employees(int num_of_employees) 
    {
        this.num_of_employees = num_of_employees;
    }

    public int getManagerID()
    {
        return managerID;
    }

    public void setManagerID(int managerID) 
    {
        this.managerID = managerID;
    }

    public boolean isActive()
    {
        return isActive;
    }

    public void setActive(boolean isActive) 
    {
        this.isActive = isActive;
    }

    @Override
    public String toString() 
    {
        return "Branch{" +
                "branchID=" + branchID +
                ", branchName='" + branchName + '\'' +
                ", city='" + city + '\'' +
                ", address='" + address + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", num_of_employees=" + num_of_employees +
                ", managerID=" + managerID +
                ", isActive=" + isActive +
                '}';
    }
}
