/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.EmployeeController;
import Controller.SuperAdminController;
import Model.Employee.EmployeeService;
import Model.EmployeeType;
import Model.SAdmin.SuperAdminService;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Dell
 */
public class AddBranchManager extends javax.swing.JFrame {

    /**
     * Creates new form AddBranchManager
     */
    int branchID;
    private void clearFields() 
    {
        nameField.setText("");
        addressField.setText("");
        phoneField.setText("");
        emailField.setText("");
        salaryField.setText("");
        addBtn.setEnabled(false); // Disable the button after clearing the fields
}

    public AddBranchManager(int branchID) {
        initComponents();
        this.branchID=branchID;
        addBtn.setEnabled(false);
        addChecks();
    }
     private void enableBtn(){
        if(!nameField.getText().isEmpty()&&!addressField.getText().isEmpty()&&phoneField.getText().length()==11&&!emailField.getText().isEmpty()&&!salaryField.getText().isEmpty()){
            addBtn.setEnabled(true);
        }
        else
        {
            addBtn.setEnabled(false);
        }
    }
    private void addChecks(){
        DocumentListener listener=new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e){
                enableBtn();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                enableBtn();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                enableBtn();
            }
        };
        nameField.getDocument().addDocumentListener(listener);
        emailField.getDocument().addDocumentListener(listener);
        addressField.getDocument().addDocumentListener(listener);
        phoneField.getDocument().addDocumentListener(listener);
        salaryField.getDocument().addDocumentListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        salaryLabel = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        addBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperAdmin- Add Branch Manager");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,200));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Add Branch Manager");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 7, -1, -1));

        nameLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        nameLabel.setText("Name");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        nameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 226, 33));

        emailLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        emailLabel.setText("Email");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        emailField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 226, 33));

        phoneLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phoneLabel.setText("Phone");
        jPanel1.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 57, -1, -1));

        phoneField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 93, 226, 33));

        salaryLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        salaryLabel.setText("Salary");
        jPanel1.add(salaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 138, -1, -1));

        salaryField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryFieldActionPerformed(evt);
            }
        });
        jPanel1.add(salaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 174, 226, 33));

        addressLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addressLabel.setText("Address");
        jPanel1.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        addressField.setColumns(20);
        addressField.setRows(5);
        addressField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(addressField);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 510, 70));

        addBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addBtn.setText("ADD");
        addBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 65, 32));

        exitBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 65, 32));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 660, 460));

        mainLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\Stores-Open-Graph-Image.jpg")); // NOI18N
        getContentPane().add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        setSize(new java.awt.Dimension(1059, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryFieldActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        String name = nameField.getText().trim();
        String address = addressField.getText().trim();
        String phoneNumber = phoneField.getText().trim();
        String email = emailField.getText().trim();
        String salaryStr = salaryField.getText().trim();
        //int branchID=0;  //it will be
        int salary;
        try 
        {
            salary = Integer.parseInt(salaryStr);
        } 
        catch (NumberFormatException e) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid salary. Please enter a numeric value.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid email format!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!phoneNumber.matches("\\d{11}")) 
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Phone number must be exactly 11 digits!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
        EmployeeController employeeeController= EmployeeController.getInstance(new EmployeeService());
        int employeeID=employeeeController.addNewEmployee(email, name, EmployeeType.BRANCH_MANAGER, branchID, phoneNumber, address, salary);
        if(employeeID==0)  //aka failed to insert
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to add branch manager. Please try again.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Branch Manager added successfully with employeeID: "+ employeeID+" and password: password_123");
            this.setVisible(false);
            SuperAdminMenu menu=new SuperAdminMenu();
            menu.setVisible(true);
        }
        clearFields();
    }//GEN-LAST:event_addBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        SuperAdminMenu menu=new SuperAdminMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBranchManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBranchManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBranchManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBranchManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddBranchManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField salaryField;
    private javax.swing.JLabel salaryLabel;
    // End of variables declaration//GEN-END:variables
}
