/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Dell
 */
public class AddBranch extends javax.swing.JFrame {

    /**
     * Creates new form AddBranch
     */
    public AddBranch() {
        initComponents();
        addBtn.setEnabled(false);
        addChecks();
    }
     private void enableBtn(){
        if(!nameField.getText().isEmpty()&&!addressField.getText().isEmpty()&&phoneField.getText().length()==11&&citydropDown.getSelectedIndex()>0){
            addBtn.setEnabled(true);
        }
        else
        {
            addBtn.setEnabled(false);
        }
    }
    private void addChecks(){
        DocumentListener listener=new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e){
                enableBtn();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                enableBtn();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                enableBtn();
            }
        };
        nameField.getDocument().addDocumentListener(listener);
        citydropDown.addActionListener(evt->enableBtn());
        addressField.getDocument().addDocumentListener(listener);
        phoneField.getDocument().addDocumentListener(listener);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        citydropDown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        phoneField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperAdmin-AddBranch");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setBackground(new java.awt.Color(255, 255, 255,50));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        mainLabel.setText("Add New Branch");
        bgPanel.add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 6, -1, -1));

        nameLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        nameLabel.setText("Branch Name");
        bgPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 70, -1, -1));

        cityLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        cityLabel.setText("City");
        bgPanel.add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 70, -1, -1));

        addressLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addressLabel.setText("Address");
        bgPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 178, -1, -1));

        phoneLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phoneLabel.setText("Phone");
        bgPanel.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 330, -1, 28));

        nameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgPanel.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 106, 200, 40));

        citydropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Lahore", "Karachi", "Islamabad", "Multan", "Faisalabad" }));
        citydropDown.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        citydropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citydropDownActionPerformed(evt);
            }
        });
        bgPanel.add(citydropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 106, 200, 40));

        addressField.setColumns(20);
        addressField.setRows(5);
        addressField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(addressField);

        bgPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 214, 326, -1));

        phoneField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgPanel.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 364, 194, 40));

        addBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addBtn.setText("ADD");
        addBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        bgPanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 427, 70, 30));

        exitBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        bgPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 427, 70, 30));

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 680, 480));

        backgroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\Stores-Open-Graph-Image.jpg")); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        setSize(new java.awt.Dimension(1059, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  
    private void citydropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citydropDownActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_citydropDownActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        //add the data to database backend logic
    }//GEN-LAST:event_addBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        SuperAdminMenu menu=new SuperAdminMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBranch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JComboBox<String> citydropDown;
    private javax.swing.JButton exitBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    // End of variables declaration//GEN-END:variables
}
