/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.EmployeeController;
import Model.Employee.EmployeeService;
import Model.EmployeeType;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import Model.UserSession;

/**
 *
 * @author Dell
 */
public class AddCashier extends javax.swing.JFrame {

    /**
     * Creates new form AddCashier
     */
    public AddCashier() {
        initComponents();
        addBtn.setEnabled(false);
        addChecks();
    }
    private void clearFields() {
    nameField.setText("");
    addressField.setText("");
    phoneField.setText("");
    emailField.setText("");
    salaryField.setText("");
}
     private void enableBtn(){
        if(!nameField.getText().isEmpty()&&!addressField.getText().isEmpty()&&phoneField.getText().length()==11&&!emailField.getText().isEmpty()&&!salaryField.getText().isEmpty()){
            addBtn.setEnabled(true);
        }
        else
        {
            addBtn.setEnabled(false);
        }
    }
    private void addChecks(){
        DocumentListener listener=new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e){
                enableBtn();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                enableBtn();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                enableBtn();
            }
        };
        nameField.getDocument().addDocumentListener(listener);
        emailField.getDocument().addDocumentListener(listener);
        addressField.getDocument().addDocumentListener(listener);
        phoneField.getDocument().addDocumentListener(listener);
        salaryField.getDocument().addDocumentListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        SalaryLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        salaryField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        addBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BranchManager-Add Cashier");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setBackground(new java.awt.Color(255, 255, 255,200));
        bgPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bgPanel.setPreferredSize(new java.awt.Dimension(660, 460));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        heading.setText("Add Cashier");
        bgPanel.add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 7, -1, -1));

        nameLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        nameLabel.setText("Name");
        bgPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 72, -1, -1));

        phoneLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phoneLabel.setText("Phone");
        bgPanel.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 72, -1, -1));

        emailLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        emailLabel.setText("Email");
        bgPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 159, -1, -1));

        SalaryLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        SalaryLabel.setText("Salary");
        bgPanel.add(SalaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 159, -1, -1));

        addressLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addressLabel.setText("Address");
        bgPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 258, -1, -1));

        nameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgPanel.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 108, 170, 33));

        phoneField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgPanel.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 108, 170, 33));

        emailField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgPanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 207, 170, 33));

        salaryField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgPanel.add(salaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 207, 170, 33));

        addressField.setColumns(20);
        addressField.setRows(5);
        jScrollPane1.setViewportView(addressField);

        bgPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 294, 463, 72));

        addBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addBtn.setText("ADD");
        addBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        bgPanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 95, 36));

        exitBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        bgPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 92, 33));

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 670, -1));
        getContentPane().add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
          BranchManagerMenu menu=new BranchManagerMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText().trim();
    String address = addressField.getText().trim();
    String phoneNumber = phoneField.getText().trim();
    String email = emailField.getText().trim();
    String salaryStr = salaryField.getText().trim();
    if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid email format!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!phoneNumber.matches("\\d{11}")) 
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Phone number must be exactly 11 digits!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    int salary;

    // Validate and parse salary
    try 
    {
        salary = Integer.parseInt(salaryStr);
    } 
    catch (NumberFormatException e) 
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid salary. Please enter a numeric value.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Add cashier using the controller
    EmployeeController employeeController = EmployeeController.getInstance(new EmployeeService());
    int branchID=UserSession.getBranchID();
    int employeeID = employeeController.addNewEmployee(email, name, EmployeeType.CASHIER, branchID, phoneNumber, address, salary);

    // Check result of adding cashier
    if (employeeID == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to add cashier. Please try again.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Cashier added successfully with employeeID: " + employeeID + " and password: password_123");
        this.setVisible(false);
        BranchManagerMenu menu = new BranchManagerMenu();
        menu.setVisible(true);
    }

    // Clear input fields
    clearFields();                                    

    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddCashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SalaryLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel heading;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField salaryField;
    // End of variables declaration//GEN-END:variables
}
 
