/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Dell
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        oldPasslabel = new javax.swing.JLabel();
        newPasslabel = new javax.swing.JLabel();
        oldPassfield = new javax.swing.JTextField();
        newPassfield = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChangePassword");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setBackground(new java.awt.Color(255, 255, 255,200));
        bgPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bgPanel.setPreferredSize(new java.awt.Dimension(660, 460));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Change Password");
        bgPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        oldPasslabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        oldPasslabel.setText("Enter Old Password");
        bgPanel.add(oldPasslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 99, -1, -1));

        newPasslabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        newPasslabel.setText("Enter New Password\n");
        bgPanel.add(newPasslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 219, -1, -1));
        bgPanel.add(oldPassfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 159, 352, -1));
        bgPanel.add(newPassfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 287, 360, -1));

        exitBtn.setText("EXIT");
        bgPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 349, -1, 41));

        submitBtn.setText("SUBMIT");
        bgPanel.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 349, -1, 41));

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        mainLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\Stores-Open-Graph-Image.jpg")); // NOI18N
        getContentPane().add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        setSize(new java.awt.Dimension(1059, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JTextField newPassfield;
    private javax.swing.JLabel newPasslabel;
    private javax.swing.JTextField oldPassfield;
    private javax.swing.JLabel oldPasslabel;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
