/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Dell
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
       // loginBtn.setEnabled(false);
        confirmPasslabel.setVisible(false);
        confirmPassfield.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        usernameField = new javax.swing.JTextField();
        userRole = new javax.swing.JComboBox<>();
        loginBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        confirmPasslabel = new javax.swing.JLabel();
        confirmPassfield = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255,200));
        loginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        mainLabel.setText("Login");
        loginPanel.add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        roleLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        roleLabel.setText("Role");
        loginPanel.add(roleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        usernameLabel.setText("Username");
        loginPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        passwordLabel.setText("Password");
        loginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        passwordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 222, 35));

        usernameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginPanel.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 222, 35));

        userRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SuperAdmin", "BranchManager", "Cashier", "DataEntryOperator" }));
        userRole.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRoleActionPerformed(evt);
            }
        });
        loginPanel.add(userRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 220, 35));

        loginBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 50, -1));

        exitBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        loginPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 50, -1));

        confirmPasslabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        confirmPasslabel.setText("Confirm Password");
        loginPanel.add(confirmPasslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        confirmPassfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmPassfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassfieldActionPerformed(evt);
            }
        });
        loginPanel.add(confirmPassfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 220, 35));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 490, 460));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\Stores-Open-Graph-Image.jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        setSize(new java.awt.Dimension(1059, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        //verify the credentials from DB
    }//GEN-LAST:event_loginBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed
     
    private void userRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRoleActionPerformed
        // TODO add your handling code here:
        String roleSelected=(String)userRole.getSelectedItem();
        
        if(roleSelected.equals("BranchManager")||roleSelected.equals("Cashier")||roleSelected.equals("DataEntryCashier")){
            passwordLabel.setText("Enter New Password");
            confirmPasslabel.setVisible(true);
            confirmPassfield.setVisible(true);
            
        }
        else
        {
            passwordLabel.setText("Password");
            confirmPasslabel.setVisible(false);
            confirmPassfield.setVisible(false);
        }
        
        //enable the login button
        //user session logic to be implemented i-e if they are logging in for the 2nd time the confirm pass thing is changed
        
    }//GEN-LAST:event_userRoleActionPerformed
     
   
    private void confirmPassfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPasswordField confirmPassfield;
    private javax.swing.JLabel confirmPasslabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JComboBox<String> userRole;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
