/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.DataEntryOperatorController;
import Controller.EmployeeController;
import Controller.SuperAdminController;
import Model.DataEntryOperator.DataEntryOperatorService;
import Model.Employee.EmployeeService;
import Model.EmployeeType;
import Model.SAdmin.SuperAdminService;
import Model.UserSession;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Login extends javax.swing.JFrame {

//<<<<<<< HEAD
    /**
     * Creates new form Login
     */
   /* public Login() {
        initComponents();
        
       // loginBtn.setEnabled(false);
        confirmPasslabel.setVisible(false);
        confirmPassfield.setVisible(false);
        
    }
=======*/
    SuperAdminController superAdminController;
    EmployeeController employeeController;
    DataEntryOperatorController deocontroller;
    /**
     * Creates new form Login
     * @param superAdminController
     * @param employeeController
     */
   
    public Login(SuperAdminController superAdminController,EmployeeController employeeController)
    {
        
        this.superAdminController=superAdminController;
        this.employeeController=employeeController;
        this.deocontroller=DataEntryOperatorController.getInstance(new DataEntryOperatorService());
        initComponents();
        
       // loginBtn.setEnabled(false);
        
    }
     public Login()
    {
        this.superAdminController=SuperAdminController.getInstance(new SuperAdminService());
        this.employeeController=EmployeeController.getInstance(new EmployeeService());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        usernameField = new javax.swing.JTextField();
        userRole = new javax.swing.JComboBox<>();
        loginBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255,200));
        loginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        mainLabel.setText("Login");
        loginPanel.add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        roleLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        roleLabel.setText("Role");
        loginPanel.add(roleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        usernameLabel.setText("Username");
        loginPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        passwordLabel.setText("Password");
        loginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        passwordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 222, 35));

        usernameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginPanel.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 222, 35));

        userRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SuperAdmin", "Branch_Manager", "Cashier", "Data_Entry_Operator" }));
        userRole.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRoleActionPerformed(evt);
            }
        });
        loginPanel.add(userRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 220, 35));

        loginBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 50, -1));

        exitBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        loginPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 50, -1));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 490, 460));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        setSize(new java.awt.Dimension(1059, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String selectedRole=(String) userRole.getSelectedItem();
        String username=usernameField.getText();
        String password=new String(passwordField.getPassword());
        if(selectedRole==null||selectedRole.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a role.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean loginSuccess=false;
        switch(selectedRole)
        {
            case "SuperAdmin":
                loginSuccess=superAdminController.verifyUser(username,password);
                if(loginSuccess)
                {
                    javax.swing.JOptionPane.showMessageDialog(this, "Login Successful", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    UserSession.create(username, selectedRole, 0); //branchID zero cause this is Admin who is not limited to a specific branch
                    new SuperAdminMenu().setVisible(true);
                    this.dispose();
                }
                break;
            case "Branch_Manager":
            case "Cashier":
            case "Data_Entry_Operator":
                int employeeID;
                try
                {
                    employeeID=Integer.parseInt(username);
                }
                catch(NumberFormatException e)
                {
                     javax.swing.JOptionPane.showMessageDialog(this, "Invalid Employee ID format.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
                int loginResult = employeeController.verifyLogin(employeeID, password, EmployeeType.valueOf(selectedRole.toUpperCase()));
                if(loginResult==0||loginResult==1) //aka login Successful
                {
                    loginSuccess=true;
                    javax.swing.JOptionPane.showMessageDialog(this, "Login Successful", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    int branchID=employeeController.getBranchID(employeeID, EmployeeType.valueOf(selectedRole.toUpperCase()));
                    UserSession.create(username, selectedRole.toUpperCase(), branchID);
                }
                if (loginResult == 0 )
                {
                    new ChangePassword().setVisible(true);  //the details you want you can take them from userSession OKAY HONEY!?
                    this.dispose();
                }
                else if(loginResult==1)
                {
                    // Proceed to the respective menu
                    switch (selectedRole)
                    {
                        case "Branch_Manager" -> new BranchManagerMenu().setVisible(true);
                        case "Cashier" -> new Cashier().setVisible(true);
                        case "Data_Entry_Operator" -> new DataEntryOperator().setVisible(true);
                        default -> {}  
                    }
                    this.dispose();
                }
                break;
        default:
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid role selected.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
    }
        //to do thing:
        //on change passwordadd a parameter of the "type" of customer and the "customerID"
        //NO NO NO NO NO JUST PUT THE VALUES IN THE USERSESSION FROM HERE THE STATIC CLASS!!!

    if (!loginSuccess) 
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Login Failed. Please check your credentials.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
           
    } 
    else
    {
       boolean res= deocontroller.saveDataIfFlagSet();
        if(res)
        {
                    JOptionPane.showMessageDialog(null, "Data saved in the database from file successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        

    }
    userRole.setSelectedIndex(-1);
    usernameField.setText("");
    passwordField.setText("");
// TODO add your handling code here:
        //verify the credentials from DB
    }//GEN-LAST:event_loginBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed
     
    private void userRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRoleActionPerformed
        // TODO add your handling code here:
       // String roleSelected=(String)userRole.getSelectedItem();
        
       // if(roleSelected.equals("BranchManager")||roleSelected.equals("Cashier")||roleSelected.equals("DataEntryCashier")){
       // String roleSelected=(String)userRole.getSelectedItem();
        
       /* if(roleSelected.equals("BranchManager")||roleSelected.equals("Cashier")||roleSelected.equals("DataEntryCashier")){
>>>>>>> umaima
            passwordLabel.setText("Enter New Password");
            confirmPasslabel.setVisible(true);
            confirmPassfield.setVisible(true);
            
        }
        else
        {
            passwordLabel.setText("Password");
            confirmPasslabel.setVisible(false);
            confirmPassfield.setVisible(false);
<<<<<<< HEAD
        }
=======
        } */
        
        //enable the login button
        //user session logic to be implemented i-e if they are logging in for the 2nd time the confirm pass thing is changed
        
    }//GEN-LAST:event_userRoleActionPerformed
/*<<<<<<< HEAD
     
   
=======*/

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed
     
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                //new Login(new SAdminController(),newEmployeeController()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JComboBox<String> userRole;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
