/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        bgLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        loadingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        loadingPercent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(153, 153, 255));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/assets/Stores-Open-Graph-Image.jpg"))); // NOI18N
        bgPanel.add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 530));
        bgPanel.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 564, 1090, 20));

        loadingLabel.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        loadingLabel.setText("Loading....");
        bgPanel.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 70, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        bgPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        loading.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        loading.setText("Loading...");
        bgPanel.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, 20));

        loadingPercent.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        loadingPercent.setText("0%");
        bgPanel.add(loadingPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       SplashScreen s=new SplashScreen();
       s.setVisible(true);
       try{
       for(int i=0;i<=100;i++){
           Thread.sleep(100);
           s.loading.setText(i+"%");
           
           if(i==20){
               s.loading.setText("Turning on Modules");
               
           }
            if(i==40){
               s.loading.setText("Loading Modules");
               
           }
            if(i==60){
                 s.loading.setText("Starting");
            }
             if(i==90){
                 s.loading.setText("Launching Application");
            }
            s.jProgressBar1.setValue(i);
       }
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
               
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JLabel loadingPercent;
    // End of variables declaration//GEN-END:variables
}
