/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.EmployeeController;
import Controller.SuperAdminController;
import Model.SAdmin.SuperAdminService;
import Model.UserSession;

/**
 *
 * @author Dell
 */
public class SuperAdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form SuperAdminMenu
     */
        int branchID;
        String status;
        SuperAdminController superAdminController;
     //EmployeeController employeeController;
    public SuperAdminMenu() {
        initComponents();
        superAdminController=SuperAdminController.getInstance(new SuperAdminService());
        activateBranchBtn.setEnabled(false);
        deactivateBranchBtn.setEnabled(false);
         addManagerBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BranchInfo = new javax.swing.JTable();
        addBranchbtn = new javax.swing.JButton();
        addManagerBtn = new javax.swing.JButton();
        activateBranchBtn = new javax.swing.JButton();
        deactivateBranchBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Admin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setBackground(new java.awt.Color(255, 255, 255,200));
        bgPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headingLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        headingLabel.setText("SuperAdmin");
        bgPanel.add(headingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 18, -1, -1));

        BranchInfo.setForeground(new java.awt.Color(255, 255, 255));
        BranchInfo.setModel(new BranchTableModel());
        BranchInfo.getTableHeader().setReorderingAllowed(false);
        BranchInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BranchInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BranchInfo);

        bgPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 753, 439));

        addBranchbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        addBranchbtn.setText("Add New Branch");
        addBranchbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBranchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBranchbtnActionPerformed(evt);
            }
        });
        bgPanel.add(addBranchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 90, 166, 50));

        addManagerBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        addManagerBtn.setText("Add Branch Manager");
        addManagerBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManagerBtnActionPerformed(evt);
            }
        });
        bgPanel.add(addManagerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 180, -1, 50));

        activateBranchBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        activateBranchBtn.setText("Activate Branch");
        activateBranchBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        activateBranchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateBranchBtnActionPerformed(evt);
            }
        });
        bgPanel.add(activateBranchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 270, 166, 50));

        deactivateBranchBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        deactivateBranchBtn.setText("Deactivate Branch");
        deactivateBranchBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deactivateBranchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateBranchBtnActionPerformed(evt);
            }
        });
        bgPanel.add(deactivateBranchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 366, 166, 50));

        logoutBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        bgPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 451, 166, 50));

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 950, 510));
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        setSize(new java.awt.Dimension(1059, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManagerBtnActionPerformed
        // TODO add your handling code here:
        //will take to other add manager screen
        AddBranchManager add=new AddBranchManager(branchID);
        this.setVisible(false);
        add.setVisible(true);
        
    }//GEN-LAST:event_addManagerBtnActionPerformed

    private void addBranchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBranchbtnActionPerformed
        // TODO add your handling code here:
        //add branch screen
        AddBranch branch=new AddBranch();
        this.setVisible(false);
        branch.setVisible(true);
        
       
    }//GEN-LAST:event_addBranchbtnActionPerformed

    private void activateBranchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateBranchBtnActionPerformed
        // TODO add your handling code here:
        //initially disabled 
        //will be enabled when a row from table is selected and status is false
        superAdminController.updateBranchStatus(branchID, true);  //aka activate
        
    }//GEN-LAST:event_activateBranchBtnActionPerformed

    private void deactivateBranchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateBranchBtnActionPerformed
        // TODO add your handling code here:
        //same as activate branch
        superAdminController.updateBranchStatus(branchID, false); //aka deactivate
    }//GEN-LAST:event_deactivateBranchBtnActionPerformed

    private void BranchInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BranchInfoMouseClicked
        // TODO add your handling code here:
        //when mouse will be clicked then something will happen
        int row = BranchInfo.getSelectedRow(); // Getting the row index
        if (row != -1) 
        {
            status = BranchInfo.getValueAt(row, 7).toString(); 
            String branchManagerId = BranchInfo.getValueAt(row, 6).toString(); 
            branchID=Integer.parseInt(BranchInfo.getValueAt(row,0 ).toString());
            // Enableing/Disableing the buttons based on status
            if ("Inactive".equalsIgnoreCase(status))
            {
                activateBranchBtn.setEnabled(true);
                deactivateBranchBtn.setEnabled(false);
            } 
            else if ("Active".equalsIgnoreCase(status)) 
            {
                activateBranchBtn.setEnabled(false);
                deactivateBranchBtn.setEnabled(true);
            }

            // Enable/Disable Add Branch Manager button based on the existence of branch manager ID
            if (branchManagerId.isEmpty() || "null".equals(branchManagerId)||branchManagerId.equals("0"))
            {
                addManagerBtn.setEnabled(true);  // Enable the button if no manager is assigned
            } 
            else
            {
                addManagerBtn.setEnabled(false);  // Disable the button if manager is already assigned
            }
    }
    }//GEN-LAST:event_BranchInfoMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        UserSession.clear();
        //showing the login screen again
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperAdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BranchInfo;
    private javax.swing.JButton activateBranchBtn;
    private javax.swing.JButton addBranchbtn;
    private javax.swing.JButton addManagerBtn;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton deactivateBranchBtn;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    // End of variables declaration//GEN-END:variables
}
