/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;

/**
 *
 * @author Dell
 */
public class UpdateDelete extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDelete
     */
    public UpdateDelete() {
        initComponents();
        updateLabel.setVisible(false);
        updateField.setVisible(false);
        oldInfoLabel.setVisible(false);
        oldinfoField.setVisible(false);
        newLabel.setVisible(false);
        newinfoField.setVisible(false);
        updateBtn.setEnabled(false);
        deletBtn.setEnabled(false);
       addChecks();
             
    }
    private void enableBtn(){
       if(actionField.getSelectedItem().equals("Update")&&roleField.getSelectedIndex()>0){
           updateLabel.setVisible(true);
           updateField.setVisible(true);
           oldInfoLabel.setText("Enter "+roleField.getSelectedItem()+" ID");
           oldInfoLabel.setVisible(true);
           oldinfoField.setVisible(true);
           newLabel.setText("Enter new "+updateField.getSelectedItem());
           newLabel.setVisible(true);
           newinfoField.setVisible(true);
           updateBtn.setEnabled(true);
           deletBtn.setEnabled(false);
           
       }
       else if(actionField.getSelectedItem().equals("Delete")&&roleField.getSelectedIndex()>0){
           updateLabel.setVisible(false);
           updateField.setVisible(false);
           oldInfoLabel.setText("Enter "+roleField.getSelectedItem()+" ID");
          oldInfoLabel.setVisible(true);
           oldinfoField.setVisible(true);
          newLabel.setVisible(false);
          newinfoField.setVisible(false);
          updateBtn.setEnabled(false);
          deletBtn.setEnabled(true);
       }
       else{
             updateLabel.setVisible(false);
        updateField.setVisible(false);
        oldInfoLabel.setVisible(false);
        oldinfoField.setVisible(false);
        newLabel.setVisible(false);
        newinfoField.setVisible(false);
        updateBtn.setEnabled(false);
        deletBtn.setEnabled(false);
       }
    }
    private void addChecks(){
         roleField.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              roleFieldActionPerformed(e);
              enableBtn();
            }
        });
         
         actionField.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              actionFieldActionPerformed(e);
              enableBtn();
            }
        });
         updateField.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              updateFieldActionPerformed(e);
              enableBtn();
            }
        });
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        roleField = new javax.swing.JComboBox<>();
        actionLabel = new javax.swing.JLabel();
        actionField = new javax.swing.JComboBox<>();
        updateLabel = new javax.swing.JLabel();
        updateField = new javax.swing.JComboBox<>();
        newLabel = new javax.swing.JLabel();
        newinfoField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        deletBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        oldInfoLabel = new javax.swing.JLabel();
        oldinfoField = new javax.swing.JTextField();
        mainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setBackground(new java.awt.Color(255, 255, 255,200));
        bgPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bgPanel.setPreferredSize(new java.awt.Dimension(660, 460));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        heading.setText("Update/Delete");
        bgPanel.add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 32, -1, -1));

        roleLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        roleLabel.setText("Role");
        bgPanel.add(roleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 109, -1, -1));

        roleField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Cashier", "DEO" }));
        roleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleFieldActionPerformed(evt);
            }
        });
        bgPanel.add(roleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 146, -1));

        actionLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        actionLabel.setText("Action");
        bgPanel.add(actionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 157, -1, -1));

        actionField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Update", "Delete" }));
        actionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionFieldActionPerformed(evt);
            }
        });
        bgPanel.add(actionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 146, -1));

        updateLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        updateLabel.setText("Update");
        bgPanel.add(updateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 205, -1, -1));

        updateField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Email", "Phone", "Address", "Salary" }));
        updateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFieldActionPerformed(evt);
            }
        });
        bgPanel.add(updateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 146, -1));

        newLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        newLabel.setText("jLabel4");
        bgPanel.add(newLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 297, -1, -1));
        bgPanel.add(newinfoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 146, -1));

        updateBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        bgPanel.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 354, 67, 38));

        deletBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deletBtn.setText("DELETE");
        deletBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgPanel.add(deletBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 354, 64, 38));

        exitBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        bgPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 354, 61, 38));

        oldInfoLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        oldInfoLabel.setText("jLabel1");
        bgPanel.add(oldInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 254, -1, 25));
        bgPanel.add(oldinfoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 146, -1));

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 690, -1));

        mainLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\Stores-Open-Graph-Image.jpg")); // NOI18N
        getContentPane().add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        setSize(new java.awt.Dimension(1059, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        //show branch manager menu
        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void roleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleFieldActionPerformed

    private void actionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionFieldActionPerformed

    private void updateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateFieldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> actionField;
    private javax.swing.JLabel actionLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton deletBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel newLabel;
    private javax.swing.JTextField newinfoField;
    private javax.swing.JLabel oldInfoLabel;
    private javax.swing.JTextField oldinfoField;
    private javax.swing.JComboBox<String> roleField;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JComboBox<String> updateField;
    private javax.swing.JLabel updateLabel;
    // End of variables declaration//GEN-END:variables
}
