/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.SuperAdminController;
import Model.Branch;
import Model.SAdmin.SuperAdminService;
import java.awt.BorderLayout;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author LENOVO
 */
public class ViewReports extends javax.swing.JFrame 
{

    /**
     * Creates new form ViewReports
     */
    SuperAdminController sadmincontroller;
    public ViewReports() 
    {
        initComponents();
        sadmincontroller=SuperAdminController.getInstance(new SuperAdminService());
        loadBranches();
    }
    private void loadBranches() {
    // Retrieve the list of branch IDs from the controller
        List<Integer> branches = sadmincontroller.getAllBranchIDs();

    // Clear the combo box before adding new items
    branchids.removeAllItems();

    // Populate the combo box with the retrieved branch IDs
    for (Integer branch : branches) 
    {
        branchids.addItem(String.valueOf(branch));
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewReports = new javax.swing.JLabel();
        branchidlabel = new javax.swing.JLabel();
        startdate = new javax.swing.JLabel();
        enddatelabel = new javax.swing.JLabel();
        generatereportbtn = new javax.swing.JButton();
        branchids = new javax.swing.JComboBox<>();
        graphPanel = new javax.swing.JPanel();
        sstartdatevar = new javax.swing.JTextField();
        enddate = new javax.swing.JTextField();
        purchaselabel = new javax.swing.JLabel();
        saleslabel = new javax.swing.JLabel();
        profitlabel = new javax.swing.JLabel();
        purchasevar = new javax.swing.JLabel();
        salesvar = new javax.swing.JLabel();
        profitvar = new javax.swing.JLabel();
        remainingstocklabel = new javax.swing.JLabel();
        remainingstockfield = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1043, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewReports.setText("View Reports");
        getContentPane().add(ViewReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        branchidlabel.setText("Branch ID: ");
        getContentPane().add(branchidlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        startdate.setText("Start Month");
        getContentPane().add(startdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        enddatelabel.setText("End Month");
        getContentPane().add(enddatelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        generatereportbtn.setText("Generate Report");
        generatereportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatereportbtnActionPerformed(evt);
            }
        });
        getContentPane().add(generatereportbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

        branchids.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(branchids, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 130, -1));

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(graphPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 690, 340));

        sstartdatevar.setText("yyyy-MM-dd");
        getContentPane().add(sstartdatevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        enddate.setText("yyyy-MM-dd");
        getContentPane().add(enddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, -1, -1));

        purchaselabel.setText("Purcases:");
        getContentPane().add(purchaselabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, -1, -1));

        saleslabel.setText("Sales:");
        getContentPane().add(saleslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, -1, -1));

        profitlabel.setText("Profit:");
        getContentPane().add(profitlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, -1, -1));
        getContentPane().add(purchasevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, -1, -1));
        getContentPane().add(salesvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, -1, -1));

        profitvar.setText("jLabel9");
        getContentPane().add(profitvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, -1, -1));

        remainingstocklabel.setText("Remaining Stock");
        getContentPane().add(remainingstocklabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, -1));

        remainingstockfield.setText("jLabel1");
        getContentPane().add(remainingstockfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generatereportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatereportbtnActionPerformed
        // TODO add your handling code here:
        String branchID = branchids.getSelectedItem().toString();
    String startDate = sstartdatevar.getText();
    String endDate = enddate.getText();
    
     DefaultCategoryDataset dataset = sadmincontroller.getDataSetReports(Integer.parseInt(branchID),startDate,endDate);//new DefaultCategoryDataset();
     
    // Create the chart
        JFreeChart chart = ChartFactory.createLineChart(
            "Branch Sales, Purchases, and Profit",  // Chart title
            "Metrics",                              // X-Axis label
            "Amount",                               // Y-Axis label
            dataset                                 // Dataset
        );

        // Display the chart in graphPanel
        graphPanel.removeAll();
        graphPanel.setLayout(new BorderLayout());
        graphPanel.add(new ChartPanel(chart), BorderLayout.CENTER);
        graphPanel.validate();
        
    }//GEN-LAST:event_generatereportbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ViewReports;
    private javax.swing.JLabel branchidlabel;
    private javax.swing.JComboBox<String> branchids;
    private javax.swing.JTextField enddate;
    private javax.swing.JLabel enddatelabel;
    private javax.swing.JButton generatereportbtn;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JLabel profitlabel;
    private javax.swing.JLabel profitvar;
    private javax.swing.JLabel purchaselabel;
    private javax.swing.JLabel purchasevar;
    private javax.swing.JLabel remainingstockfield;
    private javax.swing.JLabel remainingstocklabel;
    private javax.swing.JLabel saleslabel;
    private javax.swing.JLabel salesvar;
    private javax.swing.JTextField sstartdatevar;
    private javax.swing.JLabel startdate;
    // End of variables declaration//GEN-END:variables
}
